package ru.eruditeonline.app.presentation.composeui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * Сделано с помощью https://materialkolor.com/
 */
object ColorStandard {
    val Seed = Color(0xFF226644)

    val PrimaryLightReducedContrast = Color(0xFF286B49)
    val OnPrimaryLightReducedContrast = Color(0xFFE7FFEC)
    val PrimaryContainerLightReducedContrast = Color(0xFFACF2C6)
    val OnPrimaryContainerLightReducedContrast = Color(0xFF175D3C)
    val InversePrimaryLightReducedContrast = Color(0xFF5C9E78)
    val SecondaryLightReducedContrast = Color(0xFF4F6456)
    val OnSecondaryLightReducedContrast = Color(0xFFE7FFEC)
    val SecondaryContainerLightReducedContrast = Color(0xFFD1E8D6)
    val OnSecondaryContainerLightReducedContrast = Color(0xFF425649)
    val TertiaryLightReducedContrast = Color(0xFF546536)
    val OnTertiaryLightReducedContrast = Color(0xFFF0FFCF)
    val TertiaryContainerLightReducedContrast = Color(0xFFE1F6BA)
    val OnTertiaryContainerLightReducedContrast = Color(0xFF4D5E30)
    val BackgroundLightReducedContrast = Color(0xFFF7FAF5)
    val OnBackgroundLightReducedContrast = Color(0xFF2C352E)
    val SurfaceLightReducedContrast = Color(0xFFF7FAF5)
    val OnSurfaceLightReducedContrast = Color(0xFF2C352E)
    val SurfaceVariantLightReducedContrast = Color(0xFFDBE5DB)
    val OnSurfaceVariantLightReducedContrast = Color(0xFF58615A)
    val SurfaceTintLightReducedContrast = Color(0xFF286B49)
    val InverseSurfaceLightReducedContrast = Color(0xFF0B0F0C)
    val InverseOnSurfaceLightReducedContrast = Color(0xFF9A9E99)
    val ErrorLightReducedContrast = Color(0xFFA83836)
    val OnErrorLightReducedContrast = Color(0xFFFFF7F6)
    val ErrorContainerLightReducedContrast = Color(0xFFFA746F)
    val OnErrorContainerLightReducedContrast = Color(0xFF6E0A12)
    val OutlineLightReducedContrast = Color(0xFF747D75)
    val OutlineVariantLightReducedContrast = Color(0xFFABB4AC)
    val ScrimLightReducedContrast = Color(0xFF000000)
    val SurfaceBrightLightReducedContrast = Color(0xFFF7FAF5)
    val SurfaceContainerLightReducedContrast = Color(0xFFE9F0E8)
    val SurfaceContainerHighLightReducedContrast = Color(0xFFE2EAE2)
    val SurfaceContainerHighestLightReducedContrast = Color(0xFFDBE5DB)
    val SurfaceContainerLowLightReducedContrast = Color(0xFFF0F5EE)
    val SurfaceContainerLowestLightReducedContrast = Color(0xFFFFFFFF)
    val SurfaceDimLightReducedContrast = Color(0xFFD3DDD3)

    val PrimaryDarkReducedContrast = Color(0xFF69AC84)
    val OnPrimaryDarkReducedContrast = Color(0xFF002614)
    val PrimaryContainerDarkReducedContrast = Color(0xFF185E3D)
    val OnPrimaryContainerDarkReducedContrast = Color(0xFFADF3C7)
    val InversePrimaryDarkReducedContrast = Color(0xFF286B48)
    val SecondaryDarkReducedContrast = Color(0xFF8DA393)
    val OnSecondaryDarkReducedContrast = Color(0xFF102419)
    val SecondaryContainerDarkReducedContrast = Color(0xFF2C4033)
    val OnSecondaryContainerDarkReducedContrast = Color(0xFFAEC5B4)
    val TertiaryDarkReducedContrast = Color(0xFF92A570)
    val OnTertiaryDarkReducedContrast = Color(0xFF162400)
    val TertiaryContainerDarkReducedContrast = Color(0xFFDEF3B7)
    val OnTertiaryContainerDarkReducedContrast = Color(0xFF4C5C2F)
    val BackgroundDarkReducedContrast = Color(0xFF0B0F0C)
    val OnBackgroundDarkReducedContrast = Color(0xFFDEE8DE)
    val SurfaceDarkReducedContrast = Color(0xFF0B0F0C)
    val OnSurfaceDarkReducedContrast = Color(0xFFDEE8DE)
    val SurfaceVariantDarkReducedContrast = Color(0xFF1F2822)
    val OnSurfaceVariantDarkReducedContrast = Color(0xFFA4AEA5)
    val SurfaceTintDarkReducedContrast = Color(0xFF69AC84)
    val InverseSurfaceDarkReducedContrast = Color(0xFFF7FAF5)
    val InverseOnSurfaceDarkReducedContrast = Color(0xFF525652)
    val ErrorDarkReducedContrast = Color(0xFFFA746F)
    val OnErrorDarkReducedContrast = Color(0xFF490006)
    val ErrorContainerDarkReducedContrast = Color(0xFF871F21)
    val OnErrorContainerDarkReducedContrast = Color(0xFFFF9993)
    val OutlineDarkReducedContrast = Color(0xFF6E7870)
    val OutlineVariantDarkReducedContrast = Color(0xFF414A43)
    val ScrimDarkReducedContrast = Color(0xFF000000)
    val SurfaceBrightDarkReducedContrast = Color(0xFF252E28)
    val SurfaceContainerDarkReducedContrast = Color(0xFF151B17)
    val SurfaceContainerHighDarkReducedContrast = Color(0xFF1A211C)
    val SurfaceContainerHighestDarkReducedContrast = Color(0xFF1F2822)
    val SurfaceContainerLowDarkReducedContrast = Color(0xFF0F1511)
    val SurfaceContainerLowestDarkReducedContrast = Color(0xFF000000)
    val SurfaceDimDarkReducedContrast = Color(0xFF0B0F0C)

    val PrimaryFixedReducedContrast = Color(0xFFACF2C6)
    val PrimaryFixedDimReducedContrast = Color(0xFF9FE3B8)
    val OnPrimaryFixedReducedContrast = Color(0xFF00492C)
    val OnPrimaryFixedVariantReducedContrast = Color(0xFF236745)
    val SecondaryFixedReducedContrast = Color(0xFFD1E8D6)
    val SecondaryFixedDimReducedContrast = Color(0xFFC3DAC8)
    val OnSecondaryFixedReducedContrast = Color(0xFF2F4437)
    val OnSecondaryFixedVariantReducedContrast = Color(0xFF4B6052)
    val TertiaryFixedReducedContrast = Color(0xFFE1F6BA)
    val TertiaryFixedDimReducedContrast = Color(0xFFD3E7AD)
    val OnTertiaryFixedReducedContrast = Color(0xFF3C4B20)
    val OnTertiaryFixedVariantReducedContrast = Color(0xFF57683A)

    val reducedContrastLightColorScheme = lightColorScheme(
        primary = PrimaryLightReducedContrast,
        onPrimary = OnPrimaryLightReducedContrast,
        primaryContainer = PrimaryContainerLightReducedContrast,
        onPrimaryContainer = OnPrimaryContainerLightReducedContrast,
        inversePrimary = InversePrimaryLightReducedContrast,
        secondary = SecondaryLightReducedContrast,
        onSecondary = OnSecondaryLightReducedContrast,
        secondaryContainer = SecondaryContainerLightReducedContrast,
        onSecondaryContainer = OnSecondaryContainerLightReducedContrast,
        tertiary = TertiaryLightReducedContrast,
        onTertiary = OnTertiaryLightReducedContrast,
        tertiaryContainer = TertiaryContainerLightReducedContrast,
        onTertiaryContainer = OnTertiaryContainerLightReducedContrast,
        background = BackgroundLightReducedContrast,
        onBackground = OnBackgroundLightReducedContrast,
        surface = SurfaceLightReducedContrast,
        onSurface = OnSurfaceLightReducedContrast,
        surfaceVariant = SurfaceVariantLightReducedContrast,
        onSurfaceVariant = OnSurfaceVariantLightReducedContrast,
        surfaceTint = SurfaceTintLightReducedContrast,
        inverseSurface = InverseSurfaceLightReducedContrast,
        inverseOnSurface = InverseOnSurfaceLightReducedContrast,
        error = ErrorLightReducedContrast,
        onError = OnErrorLightReducedContrast,
        errorContainer = ErrorContainerLightReducedContrast,
        onErrorContainer = OnErrorContainerLightReducedContrast,
        outline = OutlineLightReducedContrast,
        outlineVariant = OutlineVariantLightReducedContrast,
        scrim = ScrimLightReducedContrast,
        surfaceBright = SurfaceBrightLightReducedContrast,
        surfaceContainer = SurfaceContainerLightReducedContrast,
        surfaceContainerHigh = SurfaceContainerHighLightReducedContrast,
        surfaceContainerHighest = SurfaceContainerHighestLightReducedContrast,
        surfaceContainerLow = SurfaceContainerLowLightReducedContrast,
        surfaceContainerLowest = SurfaceContainerLowestLightReducedContrast,
        surfaceDim = SurfaceDimLightReducedContrast,
        primaryFixed = PrimaryFixedReducedContrast,
        primaryFixedDim = PrimaryFixedDimReducedContrast,
        onPrimaryFixed = OnPrimaryFixedReducedContrast,
        onPrimaryFixedVariant = OnPrimaryFixedVariantReducedContrast,
        secondaryFixed = SecondaryFixedReducedContrast,
        secondaryFixedDim = SecondaryFixedDimReducedContrast,
        onSecondaryFixed = OnSecondaryFixedReducedContrast,
        onSecondaryFixedVariant = OnSecondaryFixedVariantReducedContrast,
        tertiaryFixed = TertiaryFixedReducedContrast,
        tertiaryFixedDim = TertiaryFixedDimReducedContrast,
        onTertiaryFixed = OnTertiaryFixedReducedContrast,
        onTertiaryFixedVariant = OnTertiaryFixedVariantReducedContrast,
    )

    val reducedContrastDarkColorScheme = darkColorScheme(
        primary = PrimaryDarkReducedContrast,
        onPrimary = OnPrimaryDarkReducedContrast,
        primaryContainer = PrimaryContainerDarkReducedContrast,
        onPrimaryContainer = OnPrimaryContainerDarkReducedContrast,
        inversePrimary = InversePrimaryDarkReducedContrast,
        secondary = SecondaryDarkReducedContrast,
        onSecondary = OnSecondaryDarkReducedContrast,
        secondaryContainer = SecondaryContainerDarkReducedContrast,
        onSecondaryContainer = OnSecondaryContainerDarkReducedContrast,
        tertiary = TertiaryDarkReducedContrast,
        onTertiary = OnTertiaryDarkReducedContrast,
        tertiaryContainer = TertiaryContainerDarkReducedContrast,
        onTertiaryContainer = OnTertiaryContainerDarkReducedContrast,
        background = BackgroundDarkReducedContrast,
        onBackground = OnBackgroundDarkReducedContrast,
        surface = SurfaceDarkReducedContrast,
        onSurface = OnSurfaceDarkReducedContrast,
        surfaceVariant = SurfaceVariantDarkReducedContrast,
        onSurfaceVariant = OnSurfaceVariantDarkReducedContrast,
        surfaceTint = SurfaceTintDarkReducedContrast,
        inverseSurface = InverseSurfaceDarkReducedContrast,
        inverseOnSurface = InverseOnSurfaceDarkReducedContrast,
        error = ErrorDarkReducedContrast,
        onError = OnErrorDarkReducedContrast,
        errorContainer = ErrorContainerDarkReducedContrast,
        onErrorContainer = OnErrorContainerDarkReducedContrast,
        outline = OutlineDarkReducedContrast,
        outlineVariant = OutlineVariantDarkReducedContrast,
        scrim = ScrimDarkReducedContrast,
        surfaceBright = SurfaceBrightDarkReducedContrast,
        surfaceContainer = SurfaceContainerDarkReducedContrast,
        surfaceContainerHigh = SurfaceContainerHighDarkReducedContrast,
        surfaceContainerHighest = SurfaceContainerHighestDarkReducedContrast,
        surfaceContainerLow = SurfaceContainerLowDarkReducedContrast,
        surfaceContainerLowest = SurfaceContainerLowestDarkReducedContrast,
        surfaceDim = SurfaceDimDarkReducedContrast,
        primaryFixed = PrimaryFixedReducedContrast,
        primaryFixedDim = PrimaryFixedDimReducedContrast,
        onPrimaryFixed = OnPrimaryFixedReducedContrast,
        onPrimaryFixedVariant = OnPrimaryFixedVariantReducedContrast,
        secondaryFixed = SecondaryFixedReducedContrast,
        secondaryFixedDim = SecondaryFixedDimReducedContrast,
        onSecondaryFixed = OnSecondaryFixedReducedContrast,
        onSecondaryFixedVariant = OnSecondaryFixedVariantReducedContrast,
        tertiaryFixed = TertiaryFixedReducedContrast,
        tertiaryFixedDim = TertiaryFixedDimReducedContrast,
        onTertiaryFixed = OnTertiaryFixedReducedContrast,
        onTertiaryFixedVariant = OnTertiaryFixedVariantReducedContrast,
    )
}
