package ru.eruditeonline.app.presentation.composeui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

object ColorWinter {

    val Seed = Color(0xFF0B9DE4)

    val PrimaryLightReducedContrast = Color(0xFF006595)
    val OnPrimaryLightReducedContrast = Color(0xFFF6F9FF)
    val PrimaryContainerLightReducedContrast = Color(0xFF3DB4FD)
    val OnPrimaryContainerLightReducedContrast = Color(0xFF002F49)
    val InversePrimaryLightReducedContrast = Color(0xFF0099DF)
    val SecondaryLightReducedContrast = Color(0xFF51616F)
    val OnSecondaryLightReducedContrast = Color(0xFFF6F9FF)
    val SecondaryContainerLightReducedContrast = Color(0xFFD3E5F6)
    val OnSecondaryContainerLightReducedContrast = Color(0xFF435462)
    val TertiaryLightReducedContrast = Color(0xFF595C85)
    val OnTertiaryLightReducedContrast = Color(0xFFFBF7FF)
    val TertiaryContainerLightReducedContrast = Color(0xFFCCCEFE)
    val OnTertiaryContainerLightReducedContrast = Color(0xFF42446C)
    val BackgroundLightReducedContrast = Color(0xFFF8F9FD)
    val OnBackgroundLightReducedContrast = Color(0xFF2D3339)
    val SurfaceLightReducedContrast = Color(0xFFF8F9FD)
    val OnSurfaceLightReducedContrast = Color(0xFF2D3339)
    val SurfaceVariantLightReducedContrast = Color(0xFFDDE3EB)
    val OnSurfaceVariantLightReducedContrast = Color(0xFF596067)
    val SurfaceTintLightReducedContrast = Color(0xFF006595)
    val InverseSurfaceLightReducedContrast = Color(0xFF0B0F11)
    val InverseOnSurfaceLightReducedContrast = Color(0xFF9B9DA1)
    val ErrorLightReducedContrast = Color(0xFFA83836)
    val OnErrorLightReducedContrast = Color(0xFFFFF7F6)
    val ErrorContainerLightReducedContrast = Color(0xFFFA746F)
    val OnErrorContainerLightReducedContrast = Color(0xFF6E0A12)
    val OutlineLightReducedContrast = Color(0xFF757B82)
    val OutlineVariantLightReducedContrast = Color(0xFFACB3BA)
    val ScrimLightReducedContrast = Color(0xFF000000)
    val SurfaceBrightLightReducedContrast = Color(0xFFF8F9FD)
    val SurfaceContainerLightReducedContrast = Color(0xFFEAEEF4)
    val SurfaceContainerHighLightReducedContrast = Color(0xFFE4E9EF)
    val SurfaceContainerHighestLightReducedContrast = Color(0xFFDDE3EB)
    val SurfaceContainerLowLightReducedContrast = Color(0xFFF1F4F9)
    val SurfaceContainerLowestLightReducedContrast = Color(0xFFFFFFFF)
    val SurfaceDimLightReducedContrast = Color(0xFFD4DBE3)

    val PrimaryDarkReducedContrast = Color(0xFF26A6EE)
    val OnPrimaryDarkReducedContrast = Color(0xFF002237)
    val PrimaryContainerDarkReducedContrast = Color(0xFF059CE3)
    val OnPrimaryContainerDarkReducedContrast = Color(0xFF001524)
    val InversePrimaryDarkReducedContrast = Color(0xFF006595)
    val SecondaryDarkReducedContrast = Color(0xFF8FA0B0)
    val OnSecondaryDarkReducedContrast = Color(0xFF11222E)
    val SecondaryContainerDarkReducedContrast = Color(0xFF2D3D4A)
    val OnSecondaryContainerDarkReducedContrast = Color(0xFFB0C1D2)
    val TertiaryDarkReducedContrast = Color(0xFF989AC7)
    val OnTertiaryDarkReducedContrast = Color(0xFF1A1C42)
    val TertiaryContainerDarkReducedContrast = Color(0xFFCCCEFE)
    val OnTertiaryContainerDarkReducedContrast = Color(0xFF42446C)
    val BackgroundDarkReducedContrast = Color(0xFF0B0F11)
    val OnBackgroundDarkReducedContrast = Color(0xFFE0E6EE)
    val SurfaceDarkReducedContrast = Color(0xFF0B0F11)
    val OnSurfaceDarkReducedContrast = Color(0xFFE0E6EE)
    val SurfaceVariantDarkReducedContrast = Color(0xFF20262C)
    val OnSurfaceVariantDarkReducedContrast = Color(0xFFA5ACB3)
    val SurfaceTintDarkReducedContrast = Color(0xFF26A6EE)
    val InverseSurfaceDarkReducedContrast = Color(0xFFF8F9FD)
    val InverseOnSurfaceDarkReducedContrast = Color(0xFF525559)
    val ErrorDarkReducedContrast = Color(0xFFFA746F)
    val OnErrorDarkReducedContrast = Color(0xFF490006)
    val ErrorContainerDarkReducedContrast = Color(0xFF871F21)
    val OnErrorContainerDarkReducedContrast = Color(0xFFFF9993)
    val OutlineDarkReducedContrast = Color(0xFF70767D)
    val OutlineVariantDarkReducedContrast = Color(0xFF42494F)
    val ScrimDarkReducedContrast = Color(0xFF000000)
    val SurfaceBrightDarkReducedContrast = Color(0xFF262D33)
    val SurfaceContainerDarkReducedContrast = Color(0xFF151A1F)
    val SurfaceContainerHighDarkReducedContrast = Color(0xFF1B2025)
    val SurfaceContainerHighestDarkReducedContrast = Color(0xFF20262C)
    val SurfaceContainerLowDarkReducedContrast = Color(0xFF101418)
    val SurfaceContainerLowestDarkReducedContrast = Color(0xFF000000)
    val SurfaceDimDarkReducedContrast = Color(0xFF0B0F11)

    val PrimaryFixedReducedContrast = Color(0xFF3DB4FD)
    val PrimaryFixedDimReducedContrast = Color(0xFF26A6EE)
    val OnPrimaryFixedReducedContrast = Color(0xFF00121F)
    val OnPrimaryFixedVariantReducedContrast = Color(0xFF003956)
    val SecondaryFixedReducedContrast = Color(0xFFD3E5F6)
    val SecondaryFixedDimReducedContrast = Color(0xFFC5D6E7)
    val OnSecondaryFixedReducedContrast = Color(0xFF31414F)
    val OnSecondaryFixedVariantReducedContrast = Color(0xFF4D5D6C)
    val TertiaryFixedReducedContrast = Color(0xFFCCCEFE)
    val TertiaryFixedDimReducedContrast = Color(0xFFBFC0EF)
    val OnTertiaryFixedReducedContrast = Color(0xFF2E3157)
    val OnTertiaryFixedVariantReducedContrast = Color(0xFF4B4D75)

    val reducedContrastLightColorScheme = lightColorScheme(
        primary = PrimaryLightReducedContrast,
        onPrimary = OnPrimaryLightReducedContrast,
        primaryContainer = PrimaryContainerLightReducedContrast,
        onPrimaryContainer = OnPrimaryContainerLightReducedContrast,
        inversePrimary = InversePrimaryLightReducedContrast,
        secondary = SecondaryLightReducedContrast,
        onSecondary = OnSecondaryLightReducedContrast,
        secondaryContainer = SecondaryContainerLightReducedContrast,
        onSecondaryContainer = OnSecondaryContainerLightReducedContrast,
        tertiary = TertiaryLightReducedContrast,
        onTertiary = OnTertiaryLightReducedContrast,
        tertiaryContainer = TertiaryContainerLightReducedContrast,
        onTertiaryContainer = OnTertiaryContainerLightReducedContrast,
        background = BackgroundLightReducedContrast,
        onBackground = OnBackgroundLightReducedContrast,
        surface = SurfaceLightReducedContrast,
        onSurface = OnSurfaceLightReducedContrast,
        surfaceVariant = SurfaceVariantLightReducedContrast,
        onSurfaceVariant = OnSurfaceVariantLightReducedContrast,
        surfaceTint = SurfaceTintLightReducedContrast,
        inverseSurface = InverseSurfaceLightReducedContrast,
        inverseOnSurface = InverseOnSurfaceLightReducedContrast,
        error = ErrorLightReducedContrast,
        onError = OnErrorLightReducedContrast,
        errorContainer = ErrorContainerLightReducedContrast,
        onErrorContainer = OnErrorContainerLightReducedContrast,
        outline = OutlineLightReducedContrast,
        outlineVariant = OutlineVariantLightReducedContrast,
        scrim = ScrimLightReducedContrast,
        surfaceBright = SurfaceBrightLightReducedContrast,
        surfaceContainer = SurfaceContainerLightReducedContrast,
        surfaceContainerHigh = SurfaceContainerHighLightReducedContrast,
        surfaceContainerHighest = SurfaceContainerHighestLightReducedContrast,
        surfaceContainerLow = SurfaceContainerLowLightReducedContrast,
        surfaceContainerLowest = SurfaceContainerLowestLightReducedContrast,
        surfaceDim = SurfaceDimLightReducedContrast,
        primaryFixed = PrimaryFixedReducedContrast,
        primaryFixedDim = PrimaryFixedDimReducedContrast,
        onPrimaryFixed = OnPrimaryFixedReducedContrast,
        onPrimaryFixedVariant = OnPrimaryFixedVariantReducedContrast,
        secondaryFixed = SecondaryFixedReducedContrast,
        secondaryFixedDim = SecondaryFixedDimReducedContrast,
        onSecondaryFixed = OnSecondaryFixedReducedContrast,
        onSecondaryFixedVariant = OnSecondaryFixedVariantReducedContrast,
        tertiaryFixed = TertiaryFixedReducedContrast,
        tertiaryFixedDim = TertiaryFixedDimReducedContrast,
        onTertiaryFixed = OnTertiaryFixedReducedContrast,
        onTertiaryFixedVariant = OnTertiaryFixedVariantReducedContrast,
    )

    val reducedContrastDarkColorScheme = darkColorScheme(
        primary = PrimaryDarkReducedContrast,
        onPrimary = OnPrimaryDarkReducedContrast,
        primaryContainer = PrimaryContainerDarkReducedContrast,
        onPrimaryContainer = OnPrimaryContainerDarkReducedContrast,
        inversePrimary = InversePrimaryDarkReducedContrast,
        secondary = SecondaryDarkReducedContrast,
        onSecondary = OnSecondaryDarkReducedContrast,
        secondaryContainer = SecondaryContainerDarkReducedContrast,
        onSecondaryContainer = OnSecondaryContainerDarkReducedContrast,
        tertiary = TertiaryDarkReducedContrast,
        onTertiary = OnTertiaryDarkReducedContrast,
        tertiaryContainer = TertiaryContainerDarkReducedContrast,
        onTertiaryContainer = OnTertiaryContainerDarkReducedContrast,
        background = BackgroundDarkReducedContrast,
        onBackground = OnBackgroundDarkReducedContrast,
        surface = SurfaceDarkReducedContrast,
        onSurface = OnSurfaceDarkReducedContrast,
        surfaceVariant = SurfaceVariantDarkReducedContrast,
        onSurfaceVariant = OnSurfaceVariantDarkReducedContrast,
        surfaceTint = SurfaceTintDarkReducedContrast,
        inverseSurface = InverseSurfaceDarkReducedContrast,
        inverseOnSurface = InverseOnSurfaceDarkReducedContrast,
        error = ErrorDarkReducedContrast,
        onError = OnErrorDarkReducedContrast,
        errorContainer = ErrorContainerDarkReducedContrast,
        onErrorContainer = OnErrorContainerDarkReducedContrast,
        outline = OutlineDarkReducedContrast,
        outlineVariant = OutlineVariantDarkReducedContrast,
        scrim = ScrimDarkReducedContrast,
        surfaceBright = SurfaceBrightDarkReducedContrast,
        surfaceContainer = SurfaceContainerDarkReducedContrast,
        surfaceContainerHigh = SurfaceContainerHighDarkReducedContrast,
        surfaceContainerHighest = SurfaceContainerHighestDarkReducedContrast,
        surfaceContainerLow = SurfaceContainerLowDarkReducedContrast,
        surfaceContainerLowest = SurfaceContainerLowestDarkReducedContrast,
        surfaceDim = SurfaceDimDarkReducedContrast,
        primaryFixed = PrimaryFixedReducedContrast,
        primaryFixedDim = PrimaryFixedDimReducedContrast,
        onPrimaryFixed = OnPrimaryFixedReducedContrast,
        onPrimaryFixedVariant = OnPrimaryFixedVariantReducedContrast,
        secondaryFixed = SecondaryFixedReducedContrast,
        secondaryFixedDim = SecondaryFixedDimReducedContrast,
        onSecondaryFixed = OnSecondaryFixedReducedContrast,
        onSecondaryFixedVariant = OnSecondaryFixedVariantReducedContrast,
        tertiaryFixed = TertiaryFixedReducedContrast,
        tertiaryFixedDim = TertiaryFixedDimReducedContrast,
        onTertiaryFixed = OnTertiaryFixedReducedContrast,
        onTertiaryFixedVariant = OnTertiaryFixedVariantReducedContrast,
    )
}