package ru.eruditeonline.app.presentation.composeui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * Сделано с помощью https://materialkolor.com/
 */
object ColorAutumn {
    val Seed = Color(0xFFDEAF22)

    val PrimaryLightReducedContrast = Color(0xFF775B00)
    val OnPrimaryLightReducedContrast = Color(0xFFFFF8F0)
    val PrimaryContainerLightReducedContrast = Color(0xFFF7C63A)
    val OnPrimaryContainerLightReducedContrast = Color(0xFF564100)
    val InversePrimaryLightReducedContrast = Color(0xFFB38B00)
    val SecondaryLightReducedContrast = Color(0xFF6B5E40)
    val OnSecondaryLightReducedContrast = Color(0xFFFFF8F0)
    val SecondaryContainerLightReducedContrast = Color(0xFFF3E1BB)
    val OnSecondaryContainerLightReducedContrast = Color(0xFF5D5034)
    val TertiaryLightReducedContrast = Color(0xFF825530)
    val OnTertiaryLightReducedContrast = Color(0xFFFFF7F4)
    val TertiaryContainerLightReducedContrast = Color(0xFFF9BD8F)
    val OnTertiaryContainerLightReducedContrast = Color(0xFF603816)
    val BackgroundLightReducedContrast = Color(0xFFFFF8F1)
    val OnBackgroundLightReducedContrast = Color(0xFF383225)
    val SurfaceLightReducedContrast = Color(0xFFFFF8F1)
    val OnSurfaceLightReducedContrast = Color(0xFF383225)
    val SurfaceVariantLightReducedContrast = Color(0xFFECE1CE)
    val OnSurfaceVariantLightReducedContrast = Color(0xFF665E4F)
    val SurfaceTintLightReducedContrast = Color(0xFF775B00)
    val InverseSurfaceLightReducedContrast = Color(0xFF110E08)
    val InverseOnSurfaceLightReducedContrast = Color(0xFFA39C92)
    val ErrorLightReducedContrast = Color(0xFFA73B21)
    val OnErrorLightReducedContrast = Color(0xFFFFF7F6)
    val ErrorContainerLightReducedContrast = Color(0xFFFD795A)
    val OnErrorContainerLightReducedContrast = Color(0xFF6E1400)
    val OutlineLightReducedContrast = Color(0xFF827A6A)
    val OutlineVariantLightReducedContrast = Color(0xFFBBB19F)
    val ScrimLightReducedContrast = Color(0xFF000000)
    val SurfaceBrightLightReducedContrast = Color(0xFFFFF8F1)
    val SurfaceContainerLightReducedContrast = Color(0xFFF7EDDD)
    val SurfaceContainerHighLightReducedContrast = Color(0xFFF1E7D6)
    val SurfaceContainerHighestLightReducedContrast = Color(0xFFECE1CE)
    val SurfaceContainerLowLightReducedContrast = Color(0xFFFCF2E4)
    val SurfaceContainerLowestLightReducedContrast = Color(0xFFFFFFFF)
    val SurfaceDimLightReducedContrast = Color(0xFFE4D9C6)

    val PrimaryDarkReducedContrast = Color(0xFFC49800)
    val OnPrimaryDarkReducedContrast = Color(0xFF2A1E00)
    val PrimaryContainerDarkReducedContrast = Color(0xFFCA9D04)
    val OnPrimaryContainerDarkReducedContrast = Color(0xFF302300)
    val InversePrimaryDarkReducedContrast = Color(0xFF775B00)
    val SecondaryDarkReducedContrast = Color(0xFFAC9C7A)
    val OnSecondaryDarkReducedContrast = Color(0xFF281F07)
    val SecondaryContainerDarkReducedContrast = Color(0xFF453A1F)
    val OnSecondaryContainerDarkReducedContrast = Color(0xFFCFBE9A)
    val TertiaryDarkReducedContrast = Color(0xFFC99268)
    val OnTertiaryDarkReducedContrast = Color(0xFF361800)
    val TertiaryContainerDarkReducedContrast = Color(0xFFF9BD8F)
    val OnTertiaryContainerDarkReducedContrast = Color(0xFF603816)
    val BackgroundDarkReducedContrast = Color(0xFF110E08)
    val OnBackgroundDarkReducedContrast = Color(0xFFEFE4D1)
    val SurfaceDarkReducedContrast = Color(0xFF110E08)
    val OnSurfaceDarkReducedContrast = Color(0xFFEFE4D1)
    val SurfaceVariantDarkReducedContrast = Color(0xFF2B2519)
    val OnSurfaceVariantDarkReducedContrast = Color(0xFFB4AA98)
    val SurfaceTintDarkReducedContrast = Color(0xFFC49800)
    val InverseSurfaceDarkReducedContrast = Color(0xFFFFF8F1)
    val InverseOnSurfaceDarkReducedContrast = Color(0xFF59544C)
    val ErrorDarkReducedContrast = Color(0xFFF97758)
    val OnErrorDarkReducedContrast = Color(0xFF450900)
    val ErrorContainerDarkReducedContrast = Color(0xFF85230A)
    val OnErrorContainerDarkReducedContrast = Color(0xFFFF9B82)
    val OutlineDarkReducedContrast = Color(0xFF7D7564)
    val OutlineVariantDarkReducedContrast = Color(0xFF4E4739)
    val ScrimDarkReducedContrast = Color(0xFF000000)
    val SurfaceBrightDarkReducedContrast = Color(0xFF312B1F)
    val SurfaceContainerDarkReducedContrast = Color(0xFF1D1910)
    val SurfaceContainerHighDarkReducedContrast = Color(0xFF241F15)
    val SurfaceContainerHighestDarkReducedContrast = Color(0xFF2B2519)
    val SurfaceContainerLowDarkReducedContrast = Color(0xFF17130B)
    val SurfaceContainerLowestDarkReducedContrast = Color(0xFF000000)
    val SurfaceDimDarkReducedContrast = Color(0xFF110E08)

    val PrimaryFixedReducedContrast = Color(0xFFF7C63A)
    val PrimaryFixedDimReducedContrast = Color(0xFFE8B82C)
    val OnPrimaryFixedReducedContrast = Color(0xFF3E2E00)
    val OnPrimaryFixedVariantReducedContrast = Color(0xFF614A00)
    val SecondaryFixedReducedContrast = Color(0xFFF3E1BB)
    val SecondaryFixedDimReducedContrast = Color(0xFFE4D3AE)
    val OnSecondaryFixedReducedContrast = Color(0xFF493E23)
    val OnSecondaryFixedVariantReducedContrast = Color(0xFF675A3D)
    val TertiaryFixedReducedContrast = Color(0xFFF9BD8F)
    val TertiaryFixedDimReducedContrast = Color(0xFFEAAF83)
    val OnTertiaryFixedReducedContrast = Color(0xFF492504)
    val OnTertiaryFixedVariantReducedContrast = Color(0xFF6B411E)

    val reducedContrastLightColorScheme = lightColorScheme(
        primary = PrimaryLightReducedContrast,
        onPrimary = OnPrimaryLightReducedContrast,
        primaryContainer = PrimaryContainerLightReducedContrast,
        onPrimaryContainer = OnPrimaryContainerLightReducedContrast,
        inversePrimary = InversePrimaryLightReducedContrast,
        secondary = SecondaryLightReducedContrast,
        onSecondary = OnSecondaryLightReducedContrast,
        secondaryContainer = SecondaryContainerLightReducedContrast,
        onSecondaryContainer = OnSecondaryContainerLightReducedContrast,
        tertiary = TertiaryLightReducedContrast,
        onTertiary = OnTertiaryLightReducedContrast,
        tertiaryContainer = TertiaryContainerLightReducedContrast,
        onTertiaryContainer = OnTertiaryContainerLightReducedContrast,
        background = BackgroundLightReducedContrast,
        onBackground = OnBackgroundLightReducedContrast,
        surface = SurfaceLightReducedContrast,
        onSurface = OnSurfaceLightReducedContrast,
        surfaceVariant = SurfaceVariantLightReducedContrast,
        onSurfaceVariant = OnSurfaceVariantLightReducedContrast,
        surfaceTint = SurfaceTintLightReducedContrast,
        inverseSurface = InverseSurfaceLightReducedContrast,
        inverseOnSurface = InverseOnSurfaceLightReducedContrast,
        error = ErrorLightReducedContrast,
        onError = OnErrorLightReducedContrast,
        errorContainer = ErrorContainerLightReducedContrast,
        onErrorContainer = OnErrorContainerLightReducedContrast,
        outline = OutlineLightReducedContrast,
        outlineVariant = OutlineVariantLightReducedContrast,
        scrim = ScrimLightReducedContrast,
        surfaceBright = SurfaceBrightLightReducedContrast,
        surfaceContainer = SurfaceContainerLightReducedContrast,
        surfaceContainerHigh = SurfaceContainerHighLightReducedContrast,
        surfaceContainerHighest = SurfaceContainerHighestLightReducedContrast,
        surfaceContainerLow = SurfaceContainerLowLightReducedContrast,
        surfaceContainerLowest = SurfaceContainerLowestLightReducedContrast,
        surfaceDim = SurfaceDimLightReducedContrast,
        primaryFixed = PrimaryFixedReducedContrast,
        primaryFixedDim = PrimaryFixedDimReducedContrast,
        onPrimaryFixed = OnPrimaryFixedReducedContrast,
        onPrimaryFixedVariant = OnPrimaryFixedVariantReducedContrast,
        secondaryFixed = SecondaryFixedReducedContrast,
        secondaryFixedDim = SecondaryFixedDimReducedContrast,
        onSecondaryFixed = OnSecondaryFixedReducedContrast,
        onSecondaryFixedVariant = OnSecondaryFixedVariantReducedContrast,
        tertiaryFixed = TertiaryFixedReducedContrast,
        tertiaryFixedDim = TertiaryFixedDimReducedContrast,
        onTertiaryFixed = OnTertiaryFixedReducedContrast,
        onTertiaryFixedVariant = OnTertiaryFixedVariantReducedContrast,
    )

    val reducedContrastDarkColorScheme = darkColorScheme(
        primary = PrimaryDarkReducedContrast,
        onPrimary = OnPrimaryDarkReducedContrast,
        primaryContainer = PrimaryContainerDarkReducedContrast,
        onPrimaryContainer = OnPrimaryContainerDarkReducedContrast,
        inversePrimary = InversePrimaryDarkReducedContrast,
        secondary = SecondaryDarkReducedContrast,
        onSecondary = OnSecondaryDarkReducedContrast,
        secondaryContainer = SecondaryContainerDarkReducedContrast,
        onSecondaryContainer = OnSecondaryContainerDarkReducedContrast,
        tertiary = TertiaryDarkReducedContrast,
        onTertiary = OnTertiaryDarkReducedContrast,
        tertiaryContainer = TertiaryContainerDarkReducedContrast,
        onTertiaryContainer = OnTertiaryContainerDarkReducedContrast,
        background = BackgroundDarkReducedContrast,
        onBackground = OnBackgroundDarkReducedContrast,
        surface = SurfaceDarkReducedContrast,
        onSurface = OnSurfaceDarkReducedContrast,
        surfaceVariant = SurfaceVariantDarkReducedContrast,
        onSurfaceVariant = OnSurfaceVariantDarkReducedContrast,
        surfaceTint = SurfaceTintDarkReducedContrast,
        inverseSurface = InverseSurfaceDarkReducedContrast,
        inverseOnSurface = InverseOnSurfaceDarkReducedContrast,
        error = ErrorDarkReducedContrast,
        onError = OnErrorDarkReducedContrast,
        errorContainer = ErrorContainerDarkReducedContrast,
        onErrorContainer = OnErrorContainerDarkReducedContrast,
        outline = OutlineDarkReducedContrast,
        outlineVariant = OutlineVariantDarkReducedContrast,
        scrim = ScrimDarkReducedContrast,
        surfaceBright = SurfaceBrightDarkReducedContrast,
        surfaceContainer = SurfaceContainerDarkReducedContrast,
        surfaceContainerHigh = SurfaceContainerHighDarkReducedContrast,
        surfaceContainerHighest = SurfaceContainerHighestDarkReducedContrast,
        surfaceContainerLow = SurfaceContainerLowDarkReducedContrast,
        surfaceContainerLowest = SurfaceContainerLowestDarkReducedContrast,
        surfaceDim = SurfaceDimDarkReducedContrast,
        primaryFixed = PrimaryFixedReducedContrast,
        primaryFixedDim = PrimaryFixedDimReducedContrast,
        onPrimaryFixed = OnPrimaryFixedReducedContrast,
        onPrimaryFixedVariant = OnPrimaryFixedVariantReducedContrast,
        secondaryFixed = SecondaryFixedReducedContrast,
        secondaryFixedDim = SecondaryFixedDimReducedContrast,
        onSecondaryFixed = OnSecondaryFixedReducedContrast,
        onSecondaryFixedVariant = OnSecondaryFixedVariantReducedContrast,
        tertiaryFixed = TertiaryFixedReducedContrast,
        tertiaryFixedDim = TertiaryFixedDimReducedContrast,
        onTertiaryFixed = OnTertiaryFixedReducedContrast,
        onTertiaryFixedVariant = OnTertiaryFixedVariantReducedContrast,
    )
}
